<DictionaryScreen>:
    ScreenBackground
    UserInfoPanel

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        Label:
            text: 'Словарь'
            font_size: '24sp'
            color: 0, 0, 0, 1

        # Здесь можно будет добавить список слов, кнопки и т.д.

        Button:
            text: 'Назад'
            size_hint_y: None
            height: 40
            on_press: root.goto_main_menu()